version: '3.7'

services:
  cs2203:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      network: host
    container_name: cs2203
    ports:
      - 8000:8000
    restart: unless-stopped
    env_file: .env
    volumes:
        - ../log:/var/log
        - ../../data:/backend/data

networks:
  host:
    name: host
    external: true
